import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitReact } from "../../src/emitters/react.js";
import { emitSvelte } from "../../src/emitters/svelte.js";
import type { EmitterReadyDocument, EmitterReadySnippetElement } from "../../src/ir/types.js";

/**
 * What the Svelte and React emitters consume (SPEC §12.6 / D23).
 *
 * They used to call the HTML emitter for a string and take it apart with three
 * regexes. These are the behaviours that only hold once they consume
 * `buildHTMLTree()` instead.
 */

function loadAndProcess(fixtureName: string): EmitterReadyDocument {
  const ir = JSON.parse(readFileSync(`test/fixtures/ir/${fixtureName}`, "utf-8"));
  return processDocument(ir).document;
}

function withComment(doc: EmitterReadyDocument): EmitterReadyDocument {
  const clone = structuredClone(doc);
  clone.customBlocks.push({
    type: "html-before",
    content: '<!-- desk note: do not remove --><div class="note">note</div>',
  });
  clone.customBlocks.push({
    type: "html-after",
    content: "<!-- end desk note -->",
  });
  return clone;
}

describe("framework emitters consume the node tree", () => {
  describe("comments survive", () => {
    // Regression: `/<!--[\s\S]*?-->/g` over the serialized HTML removed the
    // generator comments and, with them, any comment an author had written
    // inside their own html-before / html-after block.
    it("keeps author comments in Svelte output", () => {
      const { svelte } = emitSvelte(withComment(loadAndProcess("single-artboard-basic.json")));
      expect(svelte).toContain("<!-- desk note: do not remove -->");
      expect(svelte).toContain("<!-- end desk note -->");
      expect(svelte).toContain("<!-- Generated by all2html -->");
    });

    it("keeps author comments in React output", () => {
      const { jsx } = emitReact(withComment(loadAndProcess("single-artboard-basic.json")));
      expect(jsx).toContain("<!-- desk note: do not remove -->");
      expect(jsx).toContain("<!-- end desk note -->");
      expect(jsx).toContain("<!-- Generated by all2html -->");
    });
  });

  describe("the stylesheet is taken from the tree, not matched out of a string", () => {
    it("moves the generated CSS into the component's own style channel", () => {
      const doc = loadAndProcess("single-artboard-basic.json");
      const { svelte } = emitSvelte(doc);
      const { jsx } = emitReact(doc);

      // Present exactly once, in the framework-native place.
      expect(svelte).toContain("<style>\n:global {");
      expect(jsx).toContain("<style dangerouslySetInnerHTML={{ __html: cssText }} />");

      // And absent from the injected markup: the <style> element was removed as
      // a node, so no `<style` can survive into a chunk.
      const svelteChunks = [...svelte.matchAll(/\{@html resolveHtml\(`([\s\S]*?)`\)\}/g)].map(
        (m) => m[1],
      );
      expect(svelteChunks.length).toBeGreaterThan(0);
      for (const chunk of svelteChunks) expect(chunk).not.toContain("<style");

      const chunkBlock = jsx.slice(jsx.indexOf("const htmlChunks = ["), jsx.indexOf("];"));
      expect(chunkBlock).not.toContain("<style");
    });

    it("neutralizes </style> in the lifted CSS", () => {
      // Reading the stylesheet off the tree instead of out of the serialized
      // string is exactly where the `</style>` breakout can come back: the node
      // holds the raw CSS, and the serializer is what used to neutralize it.
      // `escaping-adversarial.json` carries `a{}</style><img src=x onerror=…>`
      // in a custom CSS block.
      const doc = loadAndProcess("escaping-adversarial.json");
      // A `</style>` that sits inside a well-formed rule survives into the
      // component, so the neutralization is what has to hold for it.
      doc.customBlocks.push({ type: "css", content: '.breakout { content: "</style>"; }' });

      const { svelte } = emitSvelte(doc);
      expect(svelte).not.toContain("</style><img");
      expect(svelte).toContain("<\\/style>");
      // The only real `</style>` is the component's own closing tag.
      expect(svelte.match(/<\/style>/g)).toHaveLength(1);

      const { jsx } = emitReact(doc);
      expect(jsx).not.toContain("</style>");
      // Backslash-escaped again for the JS template literal it is embedded in.
      expect(jsx).toMatch(/<\\+\/style>/);
    });

    it("never builds Google Fonts link tags into the markup", () => {
      const doc = loadAndProcess("single-artboard-basic.json");
      doc.settings.googleFonts = "link";
      doc.fonts = [{ sourceFont: "Inter-Regular", family: "Inter,sans-serif", weight: "400" }];

      const { svelte } = emitSvelte(doc);
      const { jsx } = emitReact(doc);

      // One occurrence each — in <svelte:head> / the JSX head constant, and
      // never inside the opaque markup chunk.
      expect(svelte.match(/fonts\.googleapis\.com\/css2/g)).toHaveLength(1);
      expect(jsx.match(/fonts\.googleapis\.com\/css2/g)).toHaveLength(1);
      expect(svelte).toContain("<svelte:head>");
      expect(jsx).toContain('<link rel="stylesheet" href={googleFontsHref} />');
    });
  });

  describe("snippet prop names are safe, unique and warned about", () => {
    function withSnippets(doc: EmitterReadyDocument, keys: string[]): EmitterReadyDocument {
      const clone = structuredClone(doc);
      for (const key of keys) {
        const snippet: EmitterReadySnippetElement = {
          type: "snippet",
          key,
          position: { x: 0, y: 0, width: 100, height: 100 },
          computedPosition: { top: "10%", left: "5%", width: "90%" },
        };
        clone.artboards[0].layers[0].elements.push(snippet);
      }
      return clone;
    }

    it("renames — and warns — when two snippet keys sanitize to one prop name", () => {
      // They used to become one prop rendering the same content in two places.
      const doc = withSnippets(loadAndProcess("single-artboard-basic.json"), [
        "my chart",
        "my-chart",
      ]);

      for (const result of [emitSvelte(doc), emitReact(doc)]) {
        const warning = result.structuredWarnings.find(
          (w) => w.code === "emit:snippet-prop-renamed",
        );
        expect(warning?.message).toContain('"my-chart"');
        expect(warning?.message).toContain("my_chart_");
      }

      // Both placeholders are addressable, and both prop names are declared.
      expect(emitSvelte(doc).svelte).toMatch(
        /let \{[^}]*\bmy_chart\b[^}]*\bmy_chart_\b[^}]*\} = \$props\(\)/,
      );
      expect(emitReact(doc).jsx).toMatch(/function \w+\([^)]*\bmy_chart\b[^)]*\bmy_chart_\b/);
    });

    it("gives both emitters the same prop name for the same key", () => {
      const doc = withSnippets(loadAndProcess("single-artboard-basic.json"), ["default", "chart"]);
      const svelteProps = emitSvelte(doc).svelte.match(/let \{ ([^}]*) \} = \$props\(\)/)?.[1];
      const reactProps = emitReact(doc).jsx.match(
        /export default function \w+\(\{ ([^}]*) \}/,
      )?.[1];
      expect(svelteProps).toContain("default_");
      expect(reactProps).toContain("default_");
    });

    it("does not warn when prop names are distinct and safe", () => {
      const doc = withSnippets(loadAndProcess("single-artboard-basic.json"), ["chart", "footer"]);
      const codes = emitSvelte(doc).structuredWarnings.map((w) => w.code);
      expect(codes).not.toContain("emit:snippet-prop-renamed");
    });
  });

  describe("documents with no replaceables stay a single chunk", () => {
    it("emits exactly one injected markup chunk", () => {
      const doc = loadAndProcess("multi-artboard-responsive.json");

      const svelteChunks = [...emitSvelte(doc).svelte.matchAll(/\{@html resolveHtml\(/g)];
      expect(svelteChunks).toHaveLength(1);

      const jsxChunks = [...emitReact(doc).jsx.matchAll(/__html: html\[\d+\]/g)];
      expect(jsxChunks).toHaveLength(1);
    });
  });
});
