import { readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitHTML } from "../../src/emitters/html.js";

const fixturesDir = resolve(import.meta.dirname, "../fixtures/ir");
const fixtureFiles = readdirSync(fixturesDir).filter((f) => f.endsWith(".json"));

/**
 * A smoke sweep: every hand-written IR fixture survives the pipeline and emits
 * plausible HTML. One test per fixture, because the failure it catches is
 * "this fixture blows up", and that is one fact per fixture.
 *
 * What used to be here and is not any more:
 *  - "string emitter matches hast emitter" compared `emitHTML` to
 *    `emitHTMLString`, which are two exported names for the same function since
 *    the emitter collapse (SPEC §12.6 / D23). It compared a function to itself.
 *    Real serializer coverage is `html-serializer.test.ts`, which pins the
 *    serializer against `hast-util-to-html` — an independent oracle.
 *  - A standalone "no NaN or undefined" test per fixture. Kept as an assertion
 *    below; non-finite *numbers* are caught far earlier and more precisely by
 *    `assertJsonPure` at every pipeline boundary (`document-json-purity.test.ts`).
 *
 * The golden-IR corpus is *not* swept here. `golden-ir.test.ts` owns it and
 * checks strictly more (Zod validation, text survival, asset references).
 */
describe("fixture coverage", () => {
  it("has fixtures to check", () => {
    expect(fixtureFiles.length).toBeGreaterThan(10);
  });

  for (const file of fixtureFiles) {
    it(`${file} processes and emits valid HTML`, () => {
      const raw = JSON.parse(readFileSync(join(fixturesDir, file), "utf-8"));
      const { document: doc } = processDocument(raw);
      expect(doc.artboards.length).toBeGreaterThan(0);

      const { html } = emitHTML(doc);
      expect(html).toContain("<!-- Generated by all2html -->");
      expect(html).toContain("<!-- End all2html -->");
      expect(html).toContain('class="ai2html"');
      expect(html.length).toBeGreaterThan(100);
      expect(html).not.toContain("NaN");
      expect(html).not.toContain("undefined");
    });
  }
});
