import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitHTML } from "../../src/emitters/html.js";
import { emitHTMLString } from "../../src/emitters/html-string.js";

const fixturesDir = resolve(import.meta.dirname, "../fixtures/ir");
const goldenDir = resolve(import.meta.dirname, "../fixtures/golden-ir");

const fixtureFiles = readdirSync(fixturesDir).filter((f) => f.endsWith(".json"));
const goldenFiles = existsSync(goldenDir)
  ? readdirSync(goldenDir).filter((f) => f.endsWith(".json"))
  : [];

function runCoverageTests(dir: string, files: string[]) {
  for (const file of files) {
    describe(file, () => {
      const raw = JSON.parse(readFileSync(join(dir, file), "utf-8"));

      it("processes through pipeline without errors", () => {
        const { document: doc } = processDocument(raw);
        expect(doc.artboards.length).toBeGreaterThan(0);
      });

      it("emits valid HTML", () => {
        const { document: doc } = processDocument(raw);
        const { html } = emitHTML(doc);
        expect(html).toContain("<!-- Generated by all2html -->");
        expect(html).toContain("<!-- End all2html -->");
        expect(html).toContain('class="ai2html"');
        expect(html.length).toBeGreaterThan(100);
      });

      it("string emitter matches hast emitter", () => {
        const { document: doc } = processDocument(raw);
        const { html: hastHtml } = emitHTML(doc);
        const { html: stringHtml } = emitHTMLString(doc);
        expect(stringHtml).toBe(hastHtml);
      });

      it("contains no NaN or undefined in HTML", () => {
        const { document: doc } = processDocument(raw);
        const { html } = emitHTML(doc);
        expect(html).not.toContain("NaN");
        expect(html).not.toContain("undefined");
      });
    });
  }
}

describe("fixture coverage", () => {
  runCoverageTests(fixturesDir, fixtureFiles);
});

describe("golden IR coverage", () => {
  runCoverageTests(goldenDir, goldenFiles);
});
