import { readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitHTML } from "../../src/emitters/html.js";
import type { Asset } from "../../src/ir/types.js";
import { loadAndValidateIR } from "../../src/ir/validate.js";

const goldenDir = resolve(import.meta.dirname, "../fixtures/golden-ir");
const goldenFiles = readdirSync(goldenDir).filter((f) => f.endsWith(".json"));

/**
 * The golden corpus is real Illustrator exporter output, so the fact worth
 * asserting per fixture is "this document still round-trips end to end": it
 * validates, it processes, the text survives to the HTML, and its assets point
 * at something. Splitting that into five `it`s reported one broken golden five
 * times and made the corpus look five times better covered than it is.
 *
 * Per-fixture *semantic* assertions (which layers, which warnings, which asset
 * paths) live in `illustrator-hardening.test.ts`, keyed by fixture name.
 */
describe("golden IR from Illustrator exporter", () => {
  it("has goldens to check", () => {
    expect(goldenFiles.length).toBeGreaterThan(10);
  });

  for (const file of goldenFiles) {
    it(`${file.replace(".json", "")} validates, processes and emits`, () => {
      const raw = JSON.parse(readFileSync(join(goldenDir, file), "utf-8"));

      const validated = loadAndValidateIR(raw);
      expect(validated.artboards.length).toBeGreaterThan(0);

      const { document: doc } = processDocument(raw);
      expect(doc.artboards.length).toBeGreaterThan(0);

      const { html } = emitHTML(doc);
      expect(html).toContain("<!-- Generated by all2html -->");
      expect(html).toContain('class="ai2html g-all2html"');
      // Text survived the round trip rather than silently vanishing.
      expect(html.match(/<p[^>]*>[^<]+<\/p>/g) ?? []).not.toHaveLength(0);
      expect(html).not.toContain("NaN");
      expect(html).not.toContain("undefined");

      // Every asset the exporter recorded is addressable and has real pixels.
      const assets = Object.values(raw.assets as Record<string, Asset>);
      expect(assets.length).toBeGreaterThan(0);
      for (const asset of assets) {
        expect(asset.path, asset.id).toBeTruthy();
        expect(asset.artboardId, asset.id).toBeTruthy();
        expect(asset.width, asset.id).toBeGreaterThan(0);
        expect(asset.height, asset.id).toBeGreaterThan(0);
      }
    });
  }
});
