import { readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitHTML } from "../../src/emitters/html.js";
import { loadAndValidateIR } from "../../src/ir/validate.js";

const goldenDir = resolve(import.meta.dirname, "../fixtures/golden-ir");
const goldenFiles = readdirSync(goldenDir).filter((f) => f.endsWith(".json"));

describe("golden IR from Illustrator exporter", () => {
  for (const file of goldenFiles) {
    const name = file.replace(".json", "");

    describe(name, () => {
      const raw = JSON.parse(readFileSync(join(goldenDir, file), "utf-8"));

      it("passes Zod validation", () => {
        const doc = loadAndValidateIR(raw);
        expect(doc.artboards.length).toBeGreaterThan(0);
      });

      it("processes through pipeline without errors", () => {
        const { document: doc, warnings } = processDocument(raw);
        expect(doc.artboards.length).toBeGreaterThan(0);
        // Warnings are okay (missing fonts, etc.) but should not crash
      });

      it("emits HTML with text content", () => {
        const { document: doc } = processDocument(raw);
        const { html } = emitHTML(doc);
        expect(html).toContain("<!-- Generated by all2html -->");
        expect(html).toContain('class="ai2html"');
        // Should have at least one <p> tag with text
        const pTags = html.match(/<p[^>]*>[^<]+<\/p>/g) || [];
        expect(pTags.length).toBeGreaterThan(0);
      });

      it("has no NaN or undefined in HTML", () => {
        const { document: doc } = processDocument(raw);
        const { html } = emitHTML(doc);
        expect(html).not.toContain("NaN");
        expect(html).not.toContain("undefined");
      });

      it("has valid asset references", () => {
        expect(Object.keys(raw.assets).length).toBeGreaterThan(0);
        for (const [, asset] of Object.entries(raw.assets) as [string, any][]) {
          expect(asset.path).toBeTruthy();
          expect(asset.artboardName).toBeTruthy();
          expect(asset.width).toBeGreaterThan(0);
          expect(asset.height).toBeGreaterThan(0);
        }
      });
    });
  }
});
