import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { processDocument } from "../../src/core/pipeline.js";
import { emitHTML } from "../../src/emitters/html.js";

const fixturesDir = resolve(import.meta.dirname, "../fixtures/ir");

function loadFixture(name: string) {
  return JSON.parse(readFileSync(resolve(fixturesDir, name), "utf-8"));
}

describe("full pipeline", () => {
  it("emits valid HTML for single artboard", () => {
    const raw = loadFixture("single-artboard-basic.json");
    const { document: doc } = processDocument(raw);
    const { html } = emitHTML(doc);

    expect(html).toContain("<!-- Generated by all2html -->");
    expect(html).toContain("<!-- End all2html -->");
    expect(html).toContain('id="g-test-graphic-box"');
    expect(html).toContain('class="ai2html g-all2html"');
    expect(html).toContain("Headline Text Here");
    expect(html).toContain("body text");
    expect(html).toContain("Label");
    expect(html).toContain("<style");
    expect(html).toContain("test-desktop.png");
  });

  it("emits responsive container queries for multi-artboard", () => {
    const raw = loadFixture("multi-artboard-responsive.json");
    const { document: doc } = processDocument(raw);
    const { html } = emitHTML(doc);

    expect(html).toContain("container-type: inline-size");
    expect(html).toContain("@container");
    expect(html).toContain("g-responsive-test-mobile");
    expect(html).toContain("g-responsive-test-tablet");
    expect(html).toContain("g-responsive-test-desktop");
    // Tablet and desktop hidden by default, mobile is visible
    expect(html).toContain("#g-responsive-test-tablet { display: none; }");
    expect(html).toContain("#g-responsive-test-desktop { display: none; }");
    // Mobile gets hidden only inside a container query, not as a default rule
    const defaultRules = html.split("@container")[0];
    expect(defaultRules).not.toContain("#g-responsive-test-mobile { display: none; }");
  });

  it("positions text elements as percentages", () => {
    const raw = loadFixture("single-artboard-basic.json");
    const { document: doc } = processDocument(raw);
    const { html } = emitHTML(doc);

    // The headline at x:50, artboard width:1200 should be ~4.1667% left
    expect(html).toContain("left:4.1667%");
    // The body text at y:100, artboard height:800 should be 12.5% top
    expect(html).toContain("top:12.5%");
  });

  it("generates font-family for known fonts", () => {
    const raw = loadFixture("single-artboard-basic.json");
    const { document: doc } = processDocument(raw);
    const { html } = emitHTML(doc);

    expect(html).toContain("arial,helvetica,sans-serif");
  });

  it("warns about unknown fonts", () => {
    const raw = loadFixture("single-artboard-basic.json");
    // Modify to use an unknown font
    raw.artboards[0].layers[0].elements[0].paragraphs[0].runs[0].fontName = "Poppins-ExtraBold";
    const { warnings } = processDocument(raw);
    expect(warnings.length).toBeGreaterThan(0);
    expect(warnings[0]).toContain("Poppins-ExtraBold");
  });

  it("preserves arbitrary metadata through the pipeline", () => {
    const raw = loadFixture("single-artboard-basic.json");
    raw.metadata.headline = "Test Headline";
    raw.metadata.credit = "Test Credit";
    raw.metadata.customField = "custom-value";
    raw.metadata.nested = { key: "value", nums: [1, 2] };

    const { document: doc } = processDocument(raw);
    expect(doc.metadata.headline).toBe("Test Headline");
    expect(doc.metadata.credit).toBe("Test Credit");
    expect(doc.metadata.customField).toBe("custom-value");
    expect(doc.metadata.nested).toEqual({ key: "value", nums: [1, 2] });
  });
});
